In [1]:
# Menggunakan numpy untuk pengolahan matriks 

import numpy as np
list1 = [0, 1, 2, 3, 4]
array1d = np.array(list1)
array1d


array([0, 1, 2, 3, 4])

In [2]:
# Tipe data
type(array1d)

numpy.ndarray

In [3]:
# Menjumlahkan elemen array
array1d + 2

array([2, 3, 4, 5, 6])

In [8]:
# Membuat array 2 dimensi
list2 = [[10, 1.5, 2.8, 3.7], [2.5, 4.56, 6.5, 8.7], [3.6, 6.7, 9.6, 12.5]]
array2d = np.array(list2)
array2d

array([[10.  ,  1.5 ,  2.8 ,  3.7 ],
       [ 2.5 ,  4.56,  6.5 ,  8.7 ],
       [ 3.6 ,  6.7 ,  9.6 , 12.5 ]])

In [9]:
# Mengatur jenis data: float/int
array2d.astype('int')

array([[10,  1,  2,  3],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [11]:
# Mengambil elemen tertentu pada array
# Elemen pertama sebanyak 1
data1 = array2d[:1, :1]
data1

data2 = array2d[:1, :2]
data2

array([[10. ,  1.5]])

In [12]:
# Operasi : mean/min/max
array2d.mean()

6.055

In [16]:
array2d.min()

1.5

In [17]:
array2d.max()

12.5

In [19]:
# Reshape dan Flattening
# Reshape : mengubah dimensi array
# Flattening : mengubah array menjadi 1 dimensi

array2d_new_dimension = array2d.reshape (4,3)
array2d_new_dimension

array([[10.  ,  1.5 ,  2.8 ],
       [ 3.7 ,  2.5 ,  4.56],
       [ 6.5 ,  8.7 ,  3.6 ],
       [ 6.7 ,  9.6 , 12.5 ]])

In [21]:
array2d_flattening = array2d.flatten()
array2d_flattening

array([10.  ,  1.5 ,  2.8 ,  3.7 ,  2.5 ,  4.56,  6.5 ,  8.7 ,  3.6 ,
        6.7 ,  9.6 , 12.5 ])

In [23]:
# Membuat array terisi data secara otomatis
np.arange(100)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Membuat array terisi data secara otomatis (print range tertentu)
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [29]:
# Membuat array dengan jumlah pasti, dengan angka antara 1 dan 50
# Sejumlah num angka
np.linspace(start=20, stop=30, num=10, dtype=int)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 30])

In [30]:
# Membuat array khusus, misal array kosong (berisi angka 0)
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
# Berisi angka 1
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
#Membuat array dengan isi bilangan acak dengan dimensi 3 X 4
np.random.rand(3, 4)

array([[0.39595905, 0.20240924, 0.22400272, 0.84911391],
       [0.05272464, 0.51064332, 0.40168697, 0.72931027],
       [0.44092172, 0.03094108, 0.3154285 , 0.65475517]])

In [35]:
# Membuat array acak dengan angla keacakan antara 3 dan 5
np.random.randint(3, 200, size=[3, 4])

array([[120,  16, 164,  23],
       [159, 110,  90,  28],
       [ 22,  88,  11, 151]])